### ISSUE TITLE
The OS is not supported

### ISSUE THREAD

**Issue by ThomasGLAllen** [defenseunicorns/zarf#2108] opened 2023-10-30 05:28 UTC
## Driving Questions
What are we hoping to validate?
I installed zarf and began to start the install of leapfrogai. There were issues with permissions, but fixed those issues, so everything worked correctly up till the end of the install and I got the following error:
---------------------------------------------------     
The OS is not supported                                                                                                                  
     ERROR:  Failed to deploy package: unable to deploy all components in this Zarf Package: unable to deploy                                 
             component download-flux: unable to run component after action: command "Extract flux binary" timed
             out after 0 seconds
tom@localhost:~> kubectl get nodes
NAME                    STATUS   ROLES                  AGE   VERSION
localhost.localdomain   Ready    control-plane,master   26h   v1.28.1+k3s1
tom@localhost:~> zarf package create .

 NOTE  Saving log file to /tmp/zarf-2023-10-29-23-43-19-970957473.log
     ERROR:  Failed to create package: unable to read the zarf.yaml file: open zarf.yaml: no such file or
             directory
----------------------------------------------------------------------
So what OS's are supported. I installed this on OpenSuse Tumbleweed. 
Just wanted to add that zarf was working correctly in that it installed the game DOOM.
Has leapfrogai been tested on a limited number of OS's? Thanks. Anxious to get this working.

## Testing Plan
User Persona: n/a
Sample Group: n/a

- [ ] Use Checklist for Tasks

## Additional context
Add any other context or screenshots about the UX test here.

Related to issue: #

**Comment by Racer159** [comment] 2023-10-30 16:40
Going to close this as a dupe of the other bug (I moved that to the package's repo since Zarf itself is doing what it is being told to do in this case).  Checking the $OS_TYPE env var returns what that script is looking for should get you moving forward on that).

**Closed by Racer159** 2023-10-30 16:40 UTC
Labels: ux
