### ISSUE TITLE
Feature/Doc Request: zarf.yaml currently requires docker.io/ prefix to be specified for images from docker hub

### ISSUE THREAD

**Issue by neoakris** [defenseunicorns/zarf#194] opened 2021-12-08 20:40 UTC
**Short Description of Minor Issue:** 

I'm investigating tooling / workflow for an Ephemeral Transport Registry (for air gap registry imports with a good UX) and Zarf looks like a great candidate, I discovered If I have this:

```
kind: ZarfPackageConfig
metadata:
  name: ephemeral-transport-registry
components:
- name: images
  required: true
  images:
  - docker.io/busybox
  - docker.io/rancher/backup-restore-operator:v1.2.0
  - rancher/cis-operator:v1.0.6
  - rancher/configmap-reload:v0.3.0-rancher4
  - rancher/coredns-coredns:1.6.2
```
Then only the docker.io/... will get uploaded 
and the imperative url will be ignored
(so only 2/5 images will get loaded into zarf's registry)

<br>

**So my feature request / ask is for either:**
1. zarf cli to get smart enough to add docker.io/ prefix to images from docker hub
2. or document the limitation / requirement that images use full domain names.

<br>

**The following is additional details of an interesting use case / example usage:**

What I'm trying to do is as follows:
1. generate an arbitrary images.txt list of container images
2. imperatively generate a declarative zarf.yaml config from images.txt
3. use zarf to declaratively populate an ephemeral registry

```bash
# provision fresh centos7 and ssh in

# become root
sudo su - 

# install zarf 0.13.3 and zarf's dependencies artifact tar
cd ~
curl -L https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/v0.13.3/zarf > zarf-cli
chmod +x zarf-cli
sudo mv zarf-cli /usr/bin/zarf
curl -L https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/v0.13.3/zarf-init.tar.zst > zarf-init.tar.zst #538mb, takes about 1m20sec

# init zarf
cd ~
zarf init --components=management --host=127.0.0.1 --confirm

# wait for zarf registry to become healthy
time while [[ $(kubectl get pods -l app=docker-registry -n=registry -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for registry to be ready (about 2 mins)..." && sleep 5; done; echo "Registry is ready"



# Create test data (that won't require registry auth for the sake of convenience)
cat > images.txt <<EOF
docker.io/busybox
docker.io/rancher/backup-restore-operator:v1.2.0
rancher/cis-operator:v1.0.6
rancher/configmap-reload:v0.3.0-rancher4
rancher/coredns-coredns:1.6.2
EOF

# If images in images.txt required auth could use this commented out stuff
# Pre-login to Authenticated Registry
# export REGISTRY1_USERNAME=REPLACE_ME
# export REGISTRY1_PASSWORD=REPLACE_ME
# zarf tools registry login registry1.dso.mil -u $REGISTRY1_USERNAME -p $REGISTRY1_PASSWORD

# Imperatively generate declarative zarf.yaml config from images.txt
TEMPLATIZED_IMAGES_LIST=$(cat images.txt | sed 's/^/  - /' )
cat > zarf.yaml <<EOF
kind: ZarfPackageConfig
metadata:
  name: ephemeral-transport-registry
components:
- name: images
  required: true
  images:
$TEMPLATIZED_IMAGES_LIST
EOF

# Eyeball validation of zarf config
head zarf.yaml

time zarf package create --confirm
time zarf package deploy zarf-package-ephemeral-transport-registry.tar.zst --confirm
# gives info about the 2 that worked, warn about the 3 the failed

# verify contents of registry
zarf tools registry catalog 127.0.0.1
```

**Comment by jeff-mccoy** [comment] 2021-12-08 23:54
I think this is a duplicate of #44.  This is currently fixed in a PR that's turned into a giant PR so I'm currently breaking it down into a smaller one to get this fix among others in sooner than later.

**Closed** 2021-12-11 03:46 UTC
