### ISSUE TITLE
Zarf incorrectly reports image download size

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#1468] opened 2023-03-23 04:07 UTC
### Environment
Device and OS: ubuntu
App version: 0.25.0
Kubernetes distro being used: n/a

### Steps to reproduce
1. create a package with images that use the same layers

### Expected result

1. zarf reports downloaded size of images

### Actual Result

1. zarf reports total size of all images layers including duplicates

### Visual Proof (screenshots, videos, text, etc)

```
[96m[96m     Pulling 61 images (7.36 GBs of 12.57 GBs)[0m[0m [36m[36m███████████████[0m[0m            [38;2;107;147;0m58%[0m | 2m20s
[96m[96m     Pulling 61 images (7.36 GBs of 12.57 GBs)[0m[0m [36m[36m███████████████[0m[0m            [38;2;105;149;0m59%[0m | 2m20s
[96m[96m     Pulling 61 images (7.36 GBs of 12.57 GBs)[0m[0m [36m[36m███████████████[0m[0m            [38;2;105;149;0m59%[0m | 2m21s
[96m[96m     Pulling 61 images (7.36 GBs of 12.57 GBs)[0m[0m [36m[36m███████████████[0m[0m            [38;2;105;149;0m59%[0m | 2m21s
                                                                                                                                                                                           
[92m[92m  ✔ [0m[0m [92m[92mPulling 61 images (12.57 GBs)[0m[0m
```

### Severity/Priority

low - visual

**Comment by Racer159** [comment] 2023-03-27 18:25
Duplicate of #1488

**Closed by Racer159** 2023-03-27 18:25 UTC
Labels: possible-bug
