### ISSUE TITLE
Package create without logging into registry1 causes SIGSEGV

### ISSUE THREAD

**Issue by david--wright** [defenseunicorns/zarf#236] opened 2022-01-20 20:59 UTC
Attempting to run `zarf package create` on the big-bang-umbrella example without logging into registry1 results in a segmentation violation. The issue is fixed by logging in per the instructions but it would be very useful to output an usable error rather than just seg faulting.

Error:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x19f1392]

goroutine 1 [running]:
github.com/google/go-containerregistry/pkg/v1/cache.(*image).ConfigName(0xc00014c280, 0xc0008bd020, 0xc000540a08, 0x0, 0x0, 0x0, 0x1)
	<autogenerated>:1 +0x32
github.com/google/go-containerregistry/pkg/v1/tarball.calculateManifest(0xc000540cd0, 0x0, 0x0, 0x0, 0xc0000a9000, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.7.0/pkg/v1/tarball/write.go:230 +0x143
github.com/google/go-containerregistry/pkg/v1/tarball.getSizeAndManifest(0xc000540cd0, 0xc00000e050, 0x1, 0xc00000e048, 0x7, 0x0, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.7.0/pkg/v1/tarball/write.go:298 +0x2f
github.com/google/go-containerregistry/pkg/v1/tarball.MultiRefWrite(0xc000540cd0, 0x21d89e0, 0xc00000e048, 0x0, 0x0, 0x0, 0x0, 0xc000540df3)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.7.0/pkg/v1/tarball/write.go:101 +0xc5
github.com/google/go-containerregistry/pkg/v1/tarball.MultiRefWriteToFile(0xc000898000, 0x45, 0xc000540cd0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.7.0/pkg/v1/tarball/write.go:64 +0xf2
github.com/google/go-containerregistry/pkg/v1/tarball.MultiWriteToFile(0xc000898000, 0x45, 0xc000540fe0, 0x0, 0x0, 0x0, 0xc000482730, 0x0)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.7.0/pkg/v1/tarball/write.go:52 +0x2cb
github.com/google/go-containerregistry/pkg/crane.MultiSave(0xc0005415f0, 0xc000898000, 0x45, 0x0, 0x0, 0x0, 0x0, 0x21d5b00)
	/go/pkg/mod/github.com/google/go-containerregistry@v0.7.0/pkg/crane/pull.go:78 +0x6df
github.com/defenseunicorns/zarf/cli/internal/images.PullAll(0xc000434ec0, 0x4, 0x4, 0xc000898000, 0x45)
	/builds/platform-one/big-bang/apps/product-tools/zarf/cli/internal/images/pull.go:29 +0x446
github.com/defenseunicorns/zarf/cli/internal/packager.addLocalAssets(0xc000888480, 0x27, 0xc000888540, 0x2d, 0xc000888570, 0x2e, 0xc000898000, 0x45, 0xc0008885a0, 0x2d, ...)
	/builds/platform-one/big-bang/apps/product-tools/zarf/cli/internal/packager/create.go:114 +0x30a
github.com/defenseunicorns/zarf/cli/internal/packager.Create(0x1)
	/builds/platform-one/big-bang/apps/product-tools/zarf/cli/internal/packager/create.go:46 +0x73e
github.com/defenseunicorns/zarf/cli/cmd.glob..func3(0x2fbb0a0, 0xc0004bb540, 0x0, 0x1)
	/builds/platform-one/big-bang/apps/product-tools/zarf/cli/cmd/package.go:27 +0x2c
github.com/spf13/cobra.(*Command).execute(0x2fbb0a0, 0xc0004bb530, 0x1, 0x1, 0x2fbb0a0, 0xc0004bb530)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2fb97a0, 0xc000138010, 0xc000539f58, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/defenseunicorns/zarf/cli/cmd.Execute()
	/builds/platform-one/big-bang/apps/product-tools/zarf/cli/cmd/root.go:44 +0xa5
main.main()
	/builds/platform-one/big-bang/apps/product-tools/zarf/cli/main.go:8 +0x25
make: *** [package-example-big-bang-umbrella] Error 2
```

**Comment by RothAndrew** [comment] 2022-01-20 21:08
Duplicate of #25 

@jeff-mccoy is this something you expect will get fixed when your big PR gets merged?

Closing this to keep the backlog clean. If you feel it should be reopened let me know, I'd be happy to do so 😄

**Closed** 2022-01-20 21:08 UTC
