### ISSUE TITLE
Zarf State includes secrets for non deployed components after `zarf init`

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/zarf#1248] opened 2023-01-23 18:22 UTC
### Environment
Device and OS: Macbook(intel), osx v13.1
App version: v0.23.5
Kubernetes distro being used: v1.24.9+k3s2
Other:

### Steps to reproduce
1. `zarf init` 
2. No to logging component, No to git-server component
3. ` k get secrets -n zarf zarf-state -o jsonpath="{ .data.state }" | base64 --decode | jq -r .`

### Expected result

Zarf State does not have values for 'gitServer' or 'loggingSecret'

### Actual Result

```
...
  "gitServer": {
    "pushUsername": "zarf-git-user",
    "pushPassword": "hh2sCy3QJLmsg9lSU9VwXQI2",
    "pullUsername": "zarf-git-read-user",
    "pullPassword": "wc5yy6D2c3s2tfrNQfqFLc!J",
    "address": "http://zarf-gitea-http.zarf.svc.cluster.local:3000",
    "internalServer": true
  },
  "registryInfo": {
    "pushUsername": "zarf-push",
    "pushPassword": "0TvBetyQpRfi7AM7y!orFRl2",
    "pullUsername": "zarf-pull",
    "pullPassword": "GjSpZSx1MHAYnlT39ZqqZmxE",
    "address": "http://127.0.0.1:31999",
    "nodePort": 31999,
    "internalRegistry": true,
    "secret": "BOG!BlKNKz9ThhR6ALtlU2He0-0IFPpXsgsa8Mh2HcbaJ7gi"
  },
  "loggingSecret": "n0v2b8FIgOHAtEzOH74HrIOz"
```
### Severity/Priority

low

### Additional Context
Discovered while implementing #1098. Solution will require code updates in the related files.  

[zarf-2023-01-23-11-05-50-26720840.log](https://github.com/defenseunicorns/zarf/files/10482586/zarf-2023-01-23-11-05-50-26720840.log)

**Comment by jeff-mccoy** [comment] 2023-01-23 19:09
Originally, that was by design because init only creates those values. So if you later wanted to add them, it wouldn't explode.

**Comment by jeff-mccoy** [comment] 2023-01-25 03:19
Unless @YrrepNoj or @Racer159 disagree, going to close this as it's by-design currently and not sure why it would be considered a bug.

**Comment by andrewg-xyz** [comment] 2023-01-25 16:28
Maybe not a bug nor a high priority issue. But the Zarf state has data inside it that indicates one thing that isn't correct, for the sake of "not blowing up" later. Seems like something that can be improved. just my 0.02

**Comment by jeff-mccoy** [comment] 2023-01-27 23:37
Going to close this as expected behavior as it better supports init as an idempotent action.

**Closed by jeff-mccoy** 2023-01-27 23:37 UTC
Labels: needs-more-info
