### ISSUE TITLE
Composable Packages from a URL

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/zarf#823] opened 2022-10-01 21:13 UTC
**Describe the solution you'd like**
I'd like to build a Zarf package referencing a package via URL.

```
  - name: games
    description: "Games package"
    import:
      path: https://raw.githubusercontent.com/defenseunicorns/zarf/master/examples/game/
...
```

**Additional context**
Short slack discussion [here](https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1664653708490319)

**Comment by Racer159** [comment] 2023-02-26 04:30
Closing this as a dupe of #1060

**Closed by Racer159** 2023-02-26 04:30 UTC
Labels: enhancement
