### ISSUE TITLE
Should Zarf be setting the "agent-ignore" label on existing namespaces on init?

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#661] opened 2022-08-05 16:47 UTC
Should Zarf be setting the "agent-ignore" label on existing namespaces on init?

On the one hand, setting the ignore label on all existing namespaces makes sense, so that you aren't borking an existing cluster with existing stuff in it when you initialize Zarf to the cluster.

On the other hand, doing so is less secure, since Zarf is ignoring things automatically without the user specifically requesting that action.

Suggestion: Perhaps create a flag that triggers this behavior? `zarf init --ignore-existing-namespaces` that defaults to not ignoring existing namespaces. That way it is an explicit action taken by the user rather than something that happens without the user really knowing about it.

Side-topic: IMO it is not clear enough that this is happening to the user. I had completely forgotten (or never learned) that this happens, causing about 2 hours of head-banging to figure out why our Zarf deployment wasn't coming back up cleanly after we did a "clean wipe" of the cluster. We had missed deleting a namespace, so when Zarf was re-initialized it added the ignore label to the namespace, causing all the pods in that namespace to go into ImagePullBackOff.

Off-topic: I would have preferred to create this as a GitHub Discussion, rather than an Issue. Can we turn Discussions back on?

**Comment by jeff-mccoy** [comment] 2022-08-05 16:53
So we actually have to have this behavior by default or else zarf would have to be able to predict what images you already have in your cluster.  Yes it would break existing stuff in the cluster on a roll of those pods, buts it's a even worse than that. If the distro uses images for jobs/provisioning PVs/load balancers/etc, those core things would break too if not in the kube-system ns, which is also exempted.  What was happening was zarf was breaking different distros because we have no way to cleanly predict when a distro might spin up some new image it needs, but so far it seems to be namespace-dependent for the most part.

**Comment by jeff-mccoy** [comment] 2022-08-05 16:54
I'm still not totally convinced we also need discussions when the slack community is pretty healthy and things naturally transition from slack threads (far better than discussions for interaction) into issues when appropriate.

**Comment by jeff-mccoy** [comment] 2022-08-05 16:57
Glancing through the docs I agree there isn't enough info about the mutating webhook.  We also could make a more obvious note in the CLI when we ignore namespaces @Madeline-UX.

**Comment by RothAndrew** [comment] 2022-08-05 17:08
> I'm still not totally convinced we also need discussions when the slack community is pretty healthy and things naturally transition from slack threads (far better than discussions for interaction) into issues when appropriate.

My vote for discussions is because they are more easily able to be found via search (and even google search) than historical slack messages. If something should live for longer than a week or so, because more people should see it as more people use the product, discussions are way better for that

**Comment by Racer159** [comment] 2022-08-05 18:16
From seeing other open source projects (GNOME being the most recent I ran into this with), I would also vote for having a discussions-esque place for talking about issues that might actually be by design along with potential considerations around them.  If you are a user of Zarf but are not in the k8s slack (which IMO would particularly be true for deployers) doing a web search for the issue wouldn't return results.

(this doesn't have to be a GitHub discussions forum though, in GNOME's case it was their subreddit that I stumbled upon first)

**Comment by JasonvanBrackel** [comment] 2022-08-17 14:52
@jeff-mccoy @RothAndrew Are good to close this and discuss Discussions at the next Zarf Office Hours?

**Closed** 2022-08-24 01:29 UTC
