### ISSUE TITLE
When publishing a package from a tarball the resulting oci image is tagged incorrectly

### ISSUE THREAD

**Issue by willejs-ec** [defenseunicorns/zarf#2446] opened 2024-04-22 08:12 UTC
### Environment
Device and OS: Linux
App version: 0.33.0
Kubernetes distro being used:
Other:

### Steps to reproduce
1. zarf package build
2. zarf package publish zarf-package-my-package-amd64-0.0.10.tar.zst oci://some-repo/my-package

### Expected result
An oci package oci://some-repo/my-package:0.0.10 is created.

### Actual Result
I have a few components in a package, component-a, component-b, component-c etc. It seems like it creates a tag with the name of a component, instead of just the version.

An oci package oci://some-repo/my-package:0.0.10-component-a is created.

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by AustinAbro321** [comment] 2024-04-22 11:54
I'm having trouble reproducing this, could you give me the metadata.name and metadata.version of the package as well as the terminal output

**Comment by lucasrod16** [comment] 2024-06-17 19:14
@willejs-ec I am unable to reproduce as well. Closing this issue but feel free to open a new issue if you encounter this again

**Closed by lucasrod16** 2024-06-17 19:14 UTC
Labels: possible-bug 🐛
