### ISSUE TITLE
[feature-request] dry-run

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/zarf#2080] opened 2023-10-17 14:24 UTC
### dry-run feature would be great.
dry-run should be an option for init and deploy. 

### solution

if `zarf init --dry-run` or `zarf deploy --dry-run` is specified, zarf will run through as much as it can and output clearly what is going on and what its plan is so we can incorporate this into CI, and help with debugging and support. It should also be possible to identify drift between multiple packages.

**Comment by Racer159** [comment] 2023-10-17 14:55
Closing as dupe of: https://github.com/defenseunicorns/zarf/issues/1980

**Closed by Racer159** 2023-10-17 14:55 UTC
Labels: enhancement
