### ISSUE TITLE
'zarf connect' command is not working when connecting to a svc

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#517] opened 2022-06-15 17:25 UTC
It looks like `zarf connect --type=svc` is still trying to connect to the pod port under the hood. Taking the inputs from a `kubectl` command and putting them into the `zarf connect` command leads to a bad tunnel being made when trying to port-forward through a service port.

### Steps to reproduce
1. Deploy standard BB-Core package 
    - This package ends up deploying has a grafana pod that is serving on port `3000` and a service that is listening on port `80`.
2. Try to `zarf connect` to the underling services

</br>

### Expected result w/ `kubectl port-forward`
`kubectl port-forward svc/monitoring-monitoring-grafana 8080:80 -n monitoring` -> 👍 Able to access grafana on localhost:8080
`kubectl port-forward pod/monitoring-monitoring-grafana-7456c6f769-x2q97 8080:3000 -n monitoring` -> 👍 able to access grafana on localhos:8080

</br>
</br>

### Expected result from `zarf connect` to a pod

`zarf connect --type=pod --name=monitoring-monitoring-grafana-7456c6f769-x2q97 --namespace=monitoring --local-port=8080 --remote-port=3000` -> 👍 able to access grafana on localhost:8080

</br>

### Unexpected result from `zarf connect` to a service

`zarf connect --type=svc --name=monitoring-monitoring-grafana --namespace=monitoring --local-port=8080 --remote-port=3000` -> 😕 able to connect to localhost:8080 even though I'm using the `svc` with the `pod port 3000`

`zarf connect --type=svc --name=monitoring-monitoring-grafana --namespace=monitoring --local-port=8080 --remote-port=80 -l trace` -> 👎 unable to connect on localhost:8080
  - also produces an interesting debug error message: 
  ```
    ✔  Creating port forwarding tunnel available at http://127.0.0.1:8080                                                                                                                               
  DEBUG   "msg"="an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod 7379dce7e40e9fc8bb57926883cf90925427d6f0af02bb8a294ec5439e08fdf3, uid : exit status 1: 2022/06/15 17:17:49 socat[24689] E connect(5, AF=2 127.0.0.1:80, 16): Connection refused\n" "error"=null
└ (/Users/jon/projects/du/zarf/zarf/src/internal/k8s/common.go:173)
  DEBUG   "msg"="lost connection to pod\n" "error"=null
└ (/Users/jon/projects/du/zarf/zarf/src/internal/k8s/common.go:173)
  ```

**Comment by jeff-mccoy** [comment] 2022-07-03 23:29
Big Bang is a pretty complex monster, can we confirm this issue exists with other services?  For example, I can't reproduce using the internal grafana like so:  `zarf connect --type=svc --name=zarf-loki-stack-grafana  --local-port=8080 --remote-port=3000`.

**Comment by jeff-mccoy** [comment] 2022-07-28 22:41
@YrrepNoj are you able to reproduce off of master still?

**Comment by jeff-mccoy** [comment] 2022-07-30 04:22
Closing for now, please re-open if the issue appears again.

**Closed by jeff-mccoy** 2022-07-30 04:22 UTC
Labels: needs-more-info, possible-bug
