### ISSUE TITLE
Support Remote Package for Composable Packages

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/zarf#381] opened 2022-03-10 20:06 UTC
In order to expand on the current composability of zarf packages the user should be able to pull zarf.yaml and dependencies from the web.  Consideration should be taken for how versioning would be handled in addition to how a SHASUM or signature configuration will be required.

**Comment by Racer159** [comment] 2023-02-26 04:31
Closing as a dupe of #1060

**Closed** 2023-02-26 04:31 UTC
Labels: enhancement, packager, needs-docs, needs-tests
