### ISSUE TITLE
Error when deploying v0.28.4 of init pkg using library Zarf

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#1972] opened 2023-08-15 02:24 UTC
### Environment
Device and OS: Mac M1
App version: 0.28.4
Kubernetes distro being used: k3d

### Steps to reproduce
When calling the [packager.Deploy](https://github.com/defenseunicorns/zarf/blob/5b5396c1466a123e5fb83adb2f02ac040a2c3e5b/src/pkg/packager/deploy.go#L41) function, I get the following error:
```
unable to parse Zarf CLI version 'unset' : Invalid Semantic Version
```
The stack trace leads to the [validateLastNonBreakingVersion](https://github.com/defenseunicorns/zarf/blob/5b5396c1466a123e5fb83adb2f02ac040a2c3e5b/src/pkg/packager/common.go#L465) function. Some notes on that function:

On v0.28.3 of the init pkg:
- the `lastNonBreakingVersion` var gets set to `""`
- the `cliVersion` var is set to "unset"

On v0.28.4 of the init pkg
- the `lastNonBreakingVersion` var gets set to `"v0.27.0"`
- the `cliVersion` var is set to "unset"

**Comment by Racer159** [comment] 2023-08-15 16:09
This is expected behavior - Zarf is trying to determine if the package that is being deployed might have issues deploying and is looking at it's version to do so - `unset` is the default value to flag that this value should be set - setting it to UnknownVersion will skip this check if you don't want to have a version at all (though this will throw errors in other places) or the version can be set to the version of Zarf (which is recommended since this value is used in checks elsewhere).

You should be able to get the info needed from `debug.BuildInfo` for now and we may take a look at refactoring this to be cleaner in the future (hence marking as tech debt instead of possible bug).

**Closed** 2023-08-25 00:55 UTC
Labels: tech-debt
