### ISSUE TITLE
Ability to easily download the init package

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1707] opened 2023-05-15 18:30 UTC
### Is your feature request related to a problem? Please describe.

I'm using Zarf as part of an automated workflow. As part of the workflow, I need to download the init package.

### Describe the solution you'd like

- **Given** a state
- **When** an action is taken
- **Then** something happens

Given I have Zarf downloaded, but not the init package

When I run `zarf tools download-init-package` (or some other equivalent command)

Then the correct init package is downloaded in the same way as if I had run `zarf init` interactively and said "yes" when asked if I want to download the init package.

![image](https://github.com/defenseunicorns/zarf/assets/16000938/e7013369-df06-4a89-9360-0cc3919372f3)

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

A gross script that uses curl would do it, but this would be much nicer.

**Comment by Racer159** [comment] 2023-05-15 22:07
Closing as dupe of https://github.com/defenseunicorns/zarf/issues/1654

**Closed by Racer159** 2023-05-15 22:07 UTC
Labels: enhancement
